config/routes.rb
Rails.application.routes.draw do
  get 'auth/:provider/callback', to: 'sessions#create'
  get 'auth/failure', to: redirect('/login')
  get 'signout', to: 'sessions#destroy', as: 'signout'
  get 'sessions/new'
  get 'sessions/create'
  get 'sessions/destroy'
  root 'top_pages#index'
  get 'top_pages/:id/download', to: 'top_pages#download', as: 'top_pages'
  get 'login', to: 'sessions#index'
  post 'login', to: 'sessions#login'
  post 'logout', to: 'sessions#logout'
  post 'password_reset', to: 'sessions#password_reset'
  get 'reset_password/:user_id', to: 'sessions#reset_password'
  post 'reset_user_password/:user_id', to: 'sessions#reset_user_password'
  get 'complite_message', to: 'sessions#complite_message'
  resources :users do
    resources :order_histories do
      get 'search', on: :collection
      post 'cart_add', on: :collection
      post 'one_cart_add', to: 'order_histories#one_cart_add'
    end
    resources :my_lists do
      delete 'product_delete'
      post 'product_add_cart', on: :collection
    end
    resources :addresses
    resources :carts do
      post 'confirm', on: :member
      get 'complite'
    end
    member do
      get 'password_edit'
      patch 'password_reset'
    end
  end
  resources :products do
    collection do
      get 'search', to: 'products#search'
      get 'quick_order', to: 'products#quick_order'
      post 'quick_order_products', to: 'products#quick_order_products'
      post 'show_create', to: 'products#show_create'
      post 'mylist_create', to: 'products#mylist_create'
    end
  end
  resources :free_pages, only: [:index]
  resources :inqueries, only: [:index] do
    get 'search', on: :collection
  end

  resources :contacts, only: [:new, :create] do
    post 'confirm', on: :collection
  end
  get 'complite', to: 'contacts#complite'
  get 'sitemap', to: 'sitemaps#sitemap'
  get 'mypage', to: 'mypages#mypage'

  # Auth0 api
  get 'api/private' => 'private#private'
  get 'api/private-scoped' => 'private#private_scoped'

  namespace :admin do
    get 'login', to: 'sessions#index'
    post 'login', to: 'sessions#login'
    post 'logout', to: 'sessions#logout'
    post 'password_reset', to: 'sessions#password_reset'
    get 'complite_message', to: 'sessions#complite_message'
    get 'dashboard', to: 'dashboards#index'
    get 'hazimeni', to: 'dashboards#hazimeni'
    post 'mongo', to: 'dashboards#mongo'
    resources :informations do
      post 'change_release', on: :member
      post 'info_title', on: :collection
      get 'download', on: :member
    end
    # post 'informations/change_release/:id', to: 'informations#change_release', as: :informations_change_release
    resources :images
    get 'banner_index', to: 'images#banner_index'
    get 'witch_new_or_edit', to: 'images#witch_new_or_edit'
    get 'banner_new', to: 'images#banner_new'
    get 'banner_edit/:id', to: 'images#banner_edit', as: 'banner_edit'
    post 'banner_create', to: 'images#banner_create'
    patch 'banner_update/:id', to: 'images#banner_update', as: 'banner_update'
    get 'product_page_edit', to: 'product_pages#edit'
    post 'product_page_create', to: 'product_pages#create'
    resources :free_pages do
      post 'change_release', on: :member
      post 'edit_change', on: :member
    end
    resources :page_contents, only: [:destroy, :create, :update]
    resources :inqueries do
      get 'select', on: :collection
    end
    resources :questions
    resources :products do
      collection do
        get 'search'
        get 'category'
        get 'category_edit'
        get 'child_category'
        post 'category_create'
        patch 'category_update'
      end
      post 'change_release', on: :member
    end
    resources :order_managements do
      collection do
        get 'user_search'
        get 'address_search'
        get 'product_search'
        get 'order_history'
        get 'order_history_search'
        post 'select_product_delete'
      end
    end
    resources :shipments do
      collection do
        get 'search'
      end
    end
    resources :members do
      collection do
        get 'search'
      end    end
    resources :groups do
      collection do
        get 'search'
      end    end
    resources :addresses do
      collection do
        get 'search'
        get 'user_search'
      end
    end
    resources :shipping_origins do
      collection do
        get 'search'
      end
    end
    resources :stock_managements do
      collection do
        get 'search'
        get 'bluk_edit'
        patch 'bluk_update'
      end
    end
    resources :shops do
      patch 'open_or_close', on: :member
    end
    resources :mail_settings
    resources :payment_method_settings
    resources :shipping_settings
    resources :cart_memos
    resources :member_ranks do
      collection do
        patch 'bluk_update'
      end
    end
    resources :holiday_settings do
      collection do
        patch 'bluk_update'
      end
    end
    resources :shop_holidays do
      post 'update_set_shop_holiday'
      patch 'update_calender_display', on: :collection
    end
    resources :users do
      get 'password_reset', on: :member
      patch 'reset', on: :member
    end
  end
end

app/models/information.rb
class Information < ApplicationRecord
  has_one :info_title
  has_many :information_attachment_files
  accepts_nested_attributes_for :information_attachment_files

  # 公開日の判定
  scope :release_period, -> { where('published_start <= ?', DateTime.current).where('? <= published_end', DateTime.current) }
end

app/controllers/admin/informations_controller.rb
class Admin::InformationsController < ApplicationController
  def index
    @errors = []
    @informations = Information.all
    @information = Information.new
    @info_title = InfoTitle.first
  end

  def info_title
    @informations = Information.all
    @information = Information.new
    @info_title = InfoTitle.first
    if @info_title.update(info_title_params)
      redirect_to admin_informations_path
    else
      render 'index'
    end
  end

  def edit
    @errors = []
    @info_title = InfoTitle.first
    @informations = Information.all
    @information = Information.find(params[:id])
  end

  def update
    @info_title = InfoTitle.first
    @informations = Information.all
    @infomation = Information.find(params[:id])

    published_start = nil
    published_end = nil

    @errors = params_valid_check(info_params)

    if @errors.present?
      render 'index' and return
    end

    if info_params[:published_start_yyyymmdd].present?
      published_start = info_params[:published_start_yyyymmdd] + ' ' + info_params[:published_start_hhmm]
    end
    if info_params[:published_end_yyyymmdd].present?
      published_end = info_params[:published_end_yyyymmdd] + ' ' +info_params[:published_end_hhmm]
    end

    if @infomation.update(detail: info_params[:detail], release_flg: info_params[:release_flg], date: info_params[:date], published_start: published_start, published_end: published_end)
      if attachment_files_add(@infomation, params)
        redirect_to edit_admin_information_path(@infomation)
      else
        render 'edit' and return
      end
    else
      render 'edit'
    end
  end

  def create
    # todo 修正
    @info_title = InfoTitle.first
    @informations = Information.all

    published_start = nil
    published_end = nil

    @errors = params_valid_check(info_params)

    if @errors.present?
      render 'index' and return
    end

    if info_params[:published_start_yyyymmdd].present?
      published_start = info_params[:published_start_yyyymmdd] + ' ' + info_params[:published_start_hhmm]
    end
    if info_params[:published_end_yyyymmdd].present?
      published_end = info_params[:published_end_yyyymmdd] + ' ' +info_params[:published_end_hhmm]
    end

    @infomation = Information.new(
      detail: info_params[:detail],
      release_flg: info_params[:release_flg],
      date: info_params[:date],
      published_start: published_start,
      published_end: published_end
    )
    if @infomation.save
      if attachment_files_new(@infomation, params)
        redirect_to edit_admin_information_path(@infomation)
      else
        render 'index' and return
      end
    else
      render 'index'
    end
  end

  def destroy
    @info_title = InfoTitle.first
    @informations = Information.all
    @infomation = Information.find(params[:id])

    if @infomation.destroy
      redirect_to admin_informations_path
    else
      render 'index'
    end
  end

  def change_release
    ActiveRecord::Base.transaction do
      info = Information.find(params[:id])
      if info.blank?
        # todo info見つからない場合のエラー文送って返す
        return redirect_to admin_informations_path
      end
      release_flg = info.release_flg
      # release_flgがtrueならfalseに、falseならtrue
      change_flg = release_flg == true ? false : true

      info.update!(release_flg: change_flg)
    end
      redirect_to admin_informations_path
  rescue
    # todo エラーの場合をかく
    render 'information/index'
  end

  def download
    @informetion = InformationAttachmentFile.find(params[:id])
    # ref: https://github.com/carrierwaveuploader/carrierwave#activerecord
    filepath = @informetion.attachment_file.current_path
    stat = File::stat(filepath)
    send_file(filepath, :filename => @informetion.filename, :length => stat.size)
  end

  private

    def info_params
      params.require(:information).permit(:detail, :release_flg, :date, :published_start_yyyymmdd, :published_start_hhmm, :published_end_yyyymmdd, :published_end_hhmm)
    end

    def info_title_params
      params.require(:info_title).permit(:title, :hyoji_count)
    end

    def attachment_files_new(info, params)
      begin
        if params[:information][:attachment_file1].present?
          InformationAttachmentFile.create(
            information_id: info.id,
            attachment_file:  params[:information][:attachment_file1],
            filename: params[:information][:attachment_file1].original_filename
          )
        end
        if params[:information][:attachment_file2].present?
          InformationAttachmentFile.create(
            information_id: info.id,
            attachment_file:  params[:information][:attachment_file2],
            filename: params[:information][:attachment_file2].original_filename
          )
        end
        if params[:information][:attachment_file3].present?
          InformationAttachmentFile.create(
            information_id: info.id,
            attachment_file:  params[:information][:attachment_file3],
            filename: params[:information][:attachment_file3].original_filename
          )
        end
        if params[:information][:attachment_file4].present?
          InformationAttachmentFile.create(
            information_id: info.id,
            attachment_file:  params[:information][:attachment_file4],
            filename: params[:information][:attachment_file4].original_filename
          )
        end
        if params[:information][:attachment_file5].present?
          InformationAttachmentFile.create(
            information_id: info.id,
            attachment_file:  params[:information][:attachment_file5],
            filename: params[:information][:attachment_file5].original_filename
          )
        end
        return true
      rescue
        return false
      end
    end

    def attachment_files_add(info, params)
      begin
        if params[:information][:attachment_file1].present? || params[:information][:attachment_file2].present? || params[:information][:attachment_file3].present? || params[:information][:attachment_file4].present? || params[:information][:attachment_file5].present?
          InformationAttachmentFile.where(information_id: info.id).destroy
        end
        if params[:information][:attachment_file1].present?
          InformationAttachmentFile.create(
            information_id: info.id,
            attachment_file:  params[:information][:attachment_file1],
            filename: params[:information][:attachment_file1].original_filename
          )
        end
        if params[:information][:attachment_file2].present?
          InformationAttachmentFile.create(
            information_id: info.id,
            attachment_file:  params[:information][:attachment_file2],
            filename: params[:information][:attachment_file2].original_filename
          )
        end
        if params[:information][:attachment_file3].present?
          InformationAttachmentFile.create(
            information_id: info.id,
            attachment_file:  params[:information][:attachment_file3],
            filename: params[:information][:attachment_file3].original_filename
          )
        end
        if params[:information][:attachment_file4].present?
          InformationAttachmentFile.create(
            information_id: info.id,
            attachment_file:  params[:information][:attachment_file4],
            filename: params[:information][:attachment_file4].original_filename
          )
        end
        if params[:information][:attachment_file5].present?
          InformationAttachmentFile.create(
            information_id: info.id,
            attachment_file:  params[:information][:attachment_file5],
            filename: params[:information][:attachment_file5].original_filename
          )
        end
        return true
      rescue
        return false
      end
    end

    def params_valid_check(info_params)
      @errors = []
      if (info_params[:published_start_yyyymmdd].present? && info_params[:published_start_hhmm].blank?) || (info_params[:published_start_yyyymmdd].blank? && info_params[:published_start_hhmm].present?)
        @errors << "掲載開始日を正しく入力してください。"
      end

      if (info_params[:published_end_yyyymmdd].present? && info_params[:published_end_hhmm].blank?) || (info_params[:published_end_yyyymmdd].blank? && info_params[:published_end_hhmm].present?)
        @errors << "掲載終了日を正しく入力してください。"
      end

      if info_params[:published_start_hhmm].present?
        if info_params[:published_start_hhmm].length < 3
          @errors << "掲載開始時刻を正しく入力してください。"
        else
          start_hhmm = info_params[:published_start_hhmm]
          # 末尾から挿入し、 "0:10" のような文字列にする。 ":"の前後で取得
          match = start_hhmm.insert(-3, ":").match(/:/)
          start_hh = match.pre_match
          if start_hh.to_i > 23
            @errors << "掲載開始時間は0~23の数字で記載してください"
          end
          start_mm = match.post_match
          if start_mm.to_i > 59
            @errors << "掲載開始時間は00~59の数字で記載してください"
          end
        end
      end

      if info_params[:published_end_hhmm].present?
        if info_params[:published_end_hhmm].length < 3
          @errors << "掲載開始時刻を正しく入力してください。"
        else
          end_hhmm = info_params[:published_end_hhmm]
          # 末尾から挿入し、 "0:10" のような文字列にする。 ":"の前後で取得
          match = end_hhmm.insert(-3, ":").match(/:/)
          end_hh = match.pre_match
          if end_hh.to_i > 23
            @errors << "掲載開始時間は0~23の数字で記載してください"
          end
          end_mm = match.post_match
          if end_mm.to_i > 59
            @errors << "掲載開始時間は00~59の数字で記載してください"
          end
        end

        return @errors
      end
    end
end

app/helpers/admin/informations_helper.rb
module Admin::InformationsHelper
end

app/views/admin/informations/_form.html.slim
table.table.table-bordered.bg-light
  tbody
    tr
      th[colspan="2"] 新着情報新規登録
    tr
      th.text-nowrap
        = f.label "日付（必須）"
      td.bg-white
        = f.date_field :date
    tr
      th = f.label "掲載期間"
      td.bg-white
        row
          = f.date_field :published_start_yyyymmdd, class: 'col-sm-3'
          = f.text_field :published_start_hhmm, class: 'col-sm-2'
          |
           ~
          = f.date_field :published_end_yyyymmdd, class: 'col-sm-3'
          = f.text_field :published_end_hhmm, class: 'col-sm-2'
        div
        small ※「yyyymmdd」の形式で入力してください。（yyyy＝年／mm＝月／dd＝日）　例）20080808
        div
        small ※「hhmm」の形式で入力してください。（hh＝時／mm＝分）　例）0930
        div
        small ※ 時間未入力の場合は、0時0分が設定されます。
    tr
      th = f.label "内容（必須）"
      td.bg-white
        = f.text_area :detail, class: 'text-area'
    tr
      th
        = f.label "添付ファイル"
        div
        |（5つまで）
      td.bg-white
        = f.file_field :attachment_file1
        = f.file_field :attachment_file2
        = f.file_field :attachment_file3
        = f.file_field :attachment_file4
        = f.file_field :attachment_file5
    tr.text-center
      = f.hidden_field :release_flg, value: true
      th[colspan="2"] = f.submit '保存'

app/views/admin/informations/_information_list.html.slim
.col-10
  br
    p.bg-secondary ◎ 新着情報
    div
      ul.border.border-5.border-muted
        p トップページの新着情報欄を変更できます。
        li.small 実際の項目の表示は、日付の降順です。（同じ日付の場合、最後に更新したものが上）
        li.small 新着情報は公開/非公開合わせて80項目まで登録が可能です。

    / informationsの総合タイトルと表示件数のみのモデルのタイトルと表示件数変更
    = form_with model: @info_title, url: info_title_admin_informations_path, method: :post, local: true do |f|
      table.table-sm.table-bordered.bg-light.image-max-size
        tbody
          tr
            th= f.label "タイトル"
            td
              = f.text_field :title, size: '45*10'
              = f.submit '保存'
            th= f.label "表示件数"
            td
              = f.text_field :hyoji_count, size: '8*10'
              = f.submit '保存'
    br

    / 情報一覧表示
    table.table.table-bordered.bg-light
      thead
        tr.text-center
          th 日付
          th 掲載期間
          th 内容
          th 添付
          th 公開
          th 変更
          th 削除
      tbody.bg-white
        - @informations.each do |im|
          tr class="text-center align-middle release_#{im.release_flg}"
            td = im.date.to_s.gsub('-', '/')
            - if im.published_start.present? || im.published_end.present?
              td
                = im.published_start.strftime('%Y/%m/%d %H:%m')
                div
                | ~
                div
                = im.published_end.strftime('%Y/%m/%d %H:%m')
            - else
              td -
            td = simple_format(im.detail)
            td
              - im.information_attachment_files.each do |iaf|
                = link_to iaf.filename, download_admin_information_path(iaf.id)
                div
            - if im.release_flg == true
              td = link_to "公開", change_release_admin_information_path(im.id), method: :post
            - else
              td = link_to "非公開", change_release_admin_information_path(im.id), method: :post
            td = link_to "変更", edit_admin_information_path(im.id)
            td = link_to "削除", admin_information_path(im.id), method: :delete

    br

app/views/admin/informations/edit.html.slim
.container
  .row
    = render 'layouts/admin_left_menu'
    = render 'admin/informations/information_list'
    .col-2
    .col-10
      - if @errors.any?
        .alert
          - @errors.each do |message|
            li = message
      = form_with model: @information, url: admin_information_path, method: :patch, local: true do |info|
        = render partial: 'form', locals: { f: info, edit: true }

app/views/admin/informations/index.html.slim
.container
  .row
    = render 'layouts/admin_left_menu'
    = render 'admin/informations/information_list'
    .col-2
    .col-10
      - if @errors.any?
        .alert
          - @errors.each do |message|
            li = message
      = form_with model: Information, url: admin_informations_path, method: :post, local: true do |info|
        = render partial: 'form', locals: { f: info, edit: false }

    / = render 'admin/informations/information_list'