config/routes.rb
Rails.application.routes.draw do
  get 'auth/:provider/callback', to: 'sessions#create'
  get 'auth/failure', to: redirect('/login')
  get 'signout', to: 'sessions#destroy', as: 'signout'
  get 'sessions/new'
  get 'sessions/create'
  get 'sessions/destroy'
  root 'top_pages#index'
  get 'top_pages/:id/download', to: 'top_pages#download', as: 'top_pages'
  get 'login', to: 'sessions#index'
  post 'login', to: 'sessions#login'
  post 'logout', to: 'sessions#logout'
  post 'password_reset', to: 'sessions#password_reset'
  get 'reset_password/:user_id', to: 'sessions#reset_password'
  post 'reset_user_password/:user_id', to: 'sessions#reset_user_password'
  get 'complite_message', to: 'sessions#complite_message'
  resources :users do
    resources :order_histories do
      get 'search', on: :collection
      post 'cart_add', on: :collection
      post 'one_cart_add', to: 'order_histories#one_cart_add'
    end
    resources :my_lists do
      delete 'product_delete'
      post 'product_add_cart', on: :collection
    end
    resources :addresses
    resources :carts do
      post 'confirm', on: :member
      get 'complite'
    end
    member do
      get 'password_edit'
      patch 'password_reset'
    end
  end
  resources :products do
    collection do
      get 'search', to: 'products#search'
      get 'quick_order', to: 'products#quick_order'
      post 'quick_order_products', to: 'products#quick_order_products'
      post 'show_create', to: 'products#show_create'
      post 'mylist_create', to: 'products#mylist_create'
    end
  end
  resources :free_pages, only: [:index]
  resources :inqueries, only: [:index] do
    get 'search', on: :collection
  end

  resources :contacts, only: [:new, :create] do
    post 'confirm', on: :collection
  end
  get 'complite', to: 'contacts#complite'
  get 'sitemap', to: 'sitemaps#sitemap'
  get 'mypage', to: 'mypages#mypage'

  # Auth0 api
  get 'api/private' => 'private#private'
  get 'api/private-scoped' => 'private#private_scoped'

  namespace :admin do
    get 'login', to: 'sessions#index'
    post 'login', to: 'sessions#login'
    post 'logout', to: 'sessions#logout'
    post 'password_reset', to: 'sessions#password_reset'
    get 'complite_message', to: 'sessions#complite_message'
    get 'dashboard', to: 'dashboards#index'
    get 'hazimeni', to: 'dashboards#hazimeni'
    post 'mongo', to: 'dashboards#mongo'
    resources :informations do
      post 'change_release', on: :member
      post 'info_title', on: :collection
      get 'download', on: :member
    end
    # post 'informations/change_release/:id', to: 'informations#change_release', as: :informations_change_release
    resources :images
    get 'banner_index', to: 'images#banner_index'
    get 'witch_new_or_edit', to: 'images#witch_new_or_edit'
    get 'banner_new', to: 'images#banner_new'
    get 'banner_edit/:id', to: 'images#banner_edit', as: 'banner_edit'
    post 'banner_create', to: 'images#banner_create'
    patch 'banner_update/:id', to: 'images#banner_update', as: 'banner_update'
    get 'product_page_edit', to: 'product_pages#edit'
    post 'product_page_create', to: 'product_pages#create'
    resources :free_pages do
      post 'change_release', on: :member
      post 'edit_change', on: :member
    end
    resources :page_contents, only: [:destroy, :create, :update]
    resources :inqueries do
      get 'select', on: :collection
    end
    resources :questions
    resources :products do
      collection do
        get 'search'
        get 'category'
        get 'category_edit'
        get 'child_category'
        post 'category_create'
        patch 'category_update'
      end
      post 'change_release', on: :member
    end
    resources :order_managements do
      collection do
        get 'user_search'
        get 'address_search'
        get 'product_search'
        get 'order_history'
        get 'order_history_search'
        post 'select_product_delete'
      end
    end
    resources :shipments do
      collection do
        get 'search'
      end
    end
    resources :members do
      collection do
        get 'search'
      end    end
    resources :groups do
      collection do
        get 'search'
      end    end
    resources :addresses do
      collection do
        get 'search'
        get 'user_search'
      end
    end
    resources :shipping_origins do
      collection do
        get 'search'
      end
    end
    resources :stock_managements do
      collection do
        get 'search'
        get 'bluk_edit'
        patch 'bluk_update'
      end
    end
    resources :shops do
      patch 'open_or_close', on: :member
    end
    resources :mail_settings
    resources :payment_method_settings
    resources :shipping_settings
    resources :cart_memos
    resources :member_ranks do
      collection do
        patch 'bluk_update'
      end
    end
    resources :holiday_settings do
      collection do
        patch 'bluk_update'
      end
    end
    resources :shop_holidays do
      post 'update_set_shop_holiday'
      patch 'update_calender_display', on: :collection
    end
    resources :users do
      get 'password_reset', on: :member
      patch 'reset', on: :member
    end
  end
end

app/models/stock_management.rb
class StockManagement < ApplicationRecord
  belongs_to :product
  has_many :stock_fluctuations
end

app/controllers/admin/stock_managements_controller.rb
class Admin::StockManagementsController < ApplicationController
  def index
    @products = Product.all
  end

  def search
  end

  def bluk_edit
    if params[:previous_action] == "search"
      @products = Product.all
    else
      @products = Product.all
    end
  end

  def show
    @product = Product.find(params[:id])
    @stock_management = StockManagement.find(params[:id])
    @stock_fluctuations = StockFluctuation.where(stock_management_id: @stock_management.id).limit(10)
  end
end

app/helpers/admin/stock_managements_helper.rb
module Admin::StockManagementsHelper
  def select_shipping_origin
    select = ShippingOrigin.pluck(:shipping_origin_name, :id).map{|so, i| [so, i]}
    select.unshift(['指定なし',99])
  end

  def select_categories
    all_category = []
    Category.all.each do |parent|
      all_category << parent.name
      if parent.child_categories.present?
        parent.child_categories.each do |child|
          all_category << "#{parent.name}/#{child.name}"
        end
      end
    end
    return all_category
  end
end

app/views/admin/stock_managements/bluk_edit.html.slim
.container
  .row
    = render 'layouts/admin_left_menu'
    .col-10
      br
      p.bg-secondary ◎ 在庫管理
      div
        ul.border.border-5.border-muted
          li.small 在庫数が豊富（無制限）の場合には、この画面からの変更できません。詳細画面で個別にチェックを外してください。
          li.small 現在の在庫数に対して追加もしくはマイナスする在庫数を入れてください。マイナスの場合には「-」を付けて保存してください。
          li.small メモを入れることで、後からの在庫数変動の履歴確認時に役立ちます。

      .text-center = link_to '一覧に戻る', admin_stock_managements_path, class: 'btn btn-primary'

      br
      = form_with model: StockManagement, url: bluk_update_admin_stock_managements_path, method: :patch, local: true do |f|
        table.table-sm.table-bordered.bg-light.image-max-size
          thead.text-center
            tr
              th 商品No.
              th 商品名
              th 出荷元
              th
                | 在庫
                div
                = f.radio_button :sabun, 1, checked: true
                | 差分入力
                = f.radio_button :sabun, 2
                | 実数入力
              th 引当
              th メモ
          tbody
            - @products.each do |p|
              tr
                td = p.product_number
                td = p.name
                /td = p.shipping_origin.shipping_origin_name
                /- if p.stock_management.unlimited_flg == 'true'
                td 豊富
                /- else
                /  td
                /    = p.stock_management.stock
                /    | +
                /    = f.text_field :change_stock
                /- if p.stock_management.unlimited_flg == 'true'
                td 豊富
                /- else
                /  td = f.text_field :change_stock_all
                td = p.stock_management.allocate
                td = f.text_field :memo, class: 'image-max-size'
            tr.text-center
              th[colspan="6"] = f.submit '保存'
            /todo 機能どうなってるのか確認後、ちゃんと動いているのか、正常なのか確認。

      br
      .text-center = link_to '一覧に戻る', admin_stock_managements_path, class: 'btn btn-primary'

app/views/admin/stock_managements/index.html.slim
.container
  .row
    = render 'layouts/admin_left_menu'
    .col-10
      br
      p.bg-secondary ◎ 在庫管理
      div
        ul.border.border-5.border-muted
          li.small 在庫数の編集、履歴の確認ができます。
          li.small 「一括更新」ボタンから在庫数の調整が行えます。検索後に「一括更新」ボタンを押した場合には、検索結果の在庫編集になります。
          li.small 「詳細」ボタンから、在庫数変動の履歴が確認できます。

      br
      = form_with model: Product, url: search_admin_stock_managements_path, method: :get, local: true do |f|
        table.table-sm.table-bordered.bg-light.image-max-size
          tr
            th = f.label 'キーワード [?]'
            td[colspan="3"] = f.text_field :keyword, class: 'image-max-size'
          tr
            th = f.label '商品状態'
            td
              = f.check_box :new_flg, {}, true, false
              | 新商品
              = f.check_box :popular_flg, {}, true, false
              | 人気商品
              = f.check_box :stock, {}, true, false
              | 在庫切れ
            th = f.label 'カテゴリ'
            td = f.select :category, select_categories
          tr
            th = f.label '出荷元'
            td[colspan="3"] = f.select :shipping_origin, select_shipping_origin
          tr.text-center
            th[colspan="4"] = f.submit '検索'

      br
      .text-center = link_to '一括更新', bluk_edit_admin_stock_managements_path(previous_action: params[:action]), class: 'btn btn-primary'

      br
      table.table-sm.table-bordered.bg-light.image-max-size
        thead
          tr
            th 商品No.
            th 商品名
            th 出荷元
            th 在庫
            th 引当
            th 詳細
        tbody
          - @products.each do |p|
            tr
              td = p.product_number
              td = p.name
              - if p.shipping_origin.present?
                td = p.shipping_origin.shipping_origin_name
              - else
                td
              td = p.stock_management.stock
              td 引き当て
              td = link_to '詳細', admin_stock_management_path(p)


      br
      .text-center = link_to '一括更新', bluk_edit_admin_stock_managements_path(previous_action: params[:action]), class: 'btn btn-primary'
      / todo 一括更新は現ページで表示されている情報をそのまま一括ページで表示させる。なので機能合っているか確認。

app/views/admin/stock_managements/show.html.slim
.container
  .row
    = render 'layouts/admin_left_menu'
    .col-10
      br
      p.bg-secondary ◎ 在庫管理

      table.table-sm.table-bordered.bg-light.image-max-size
        thead
          tr
            th 在庫管理 ／ 詳細
          tr
            td 商品No.
            td 商品名
            td 出荷元
            td 在庫
            td 引当
          tr
            td = @product.product_number
            td = @product.name
            td = @product.shipping_origin.shipping_origin_name
            td = @product.stock_management.stock
            td = @product.stock_management.allocate

      br
      table.table-sm.table-bordered.bg-light.image-max-size
        thead
          tr
            th[colspan="3"] 在庫編集
        tbody
          = form_with model: @stock_management, url: admin_stock_management_path, method: :patch, local: true do |f|
            tr
              th = f.label '無制限'
              th
                = f.label '在庫数'
                div
                = f.radio_button :sabun, 1, checked: true
                | 差分入力
                = f.radio_button :sabun, 2
                | 実数入力
              th = f.label 'メモ[?]'
            tr
              td = f.check_box :unlimited, {}, true, false
              td = f.text_field :aiueo, placeholder: "現在の在庫数：#{@stock_management.stock}"
              td = f.text_area :memo, class: 'text-area'
            tr.text-center
              th[colspan="3"] = f.submit '保存'

      br
      .text-center = link_to '戻る', admin_stock_managements_path, class: 'btn btn-primary'

      / todo 表示できるようにする（多分できてない。）
      br
      p 日付	区分	受注番号	移動数量	対象	在庫	引当[?]	メモ
      - @stock_fluctuations.each do |sf|
        = sf.created_at.strftime('%Y%m%d')