config/routes.rb
Rails.application.routes.draw do
  get 'auth/:provider/callback', to: 'sessions#create'
  get 'auth/failure', to: redirect('/login')
  get 'signout', to: 'sessions#destroy', as: 'signout'
  get 'sessions/new'
  get 'sessions/create'
  get 'sessions/destroy'
  root 'top_pages#index'
  get 'top_pages/:id/download', to: 'top_pages#download', as: 'top_pages'
  get 'login', to: 'sessions#index'
  post 'login', to: 'sessions#login'
  post 'logout', to: 'sessions#logout'
  post 'password_reset', to: 'sessions#password_reset'
  get 'reset_password/:user_id', to: 'sessions#reset_password'
  post 'reset_user_password/:user_id', to: 'sessions#reset_user_password'
  get 'complite_message', to: 'sessions#complite_message'
  resources :users do
    resources :order_histories do
      get 'search', on: :collection
      post 'cart_add', on: :collection
      post 'one_cart_add', to: 'order_histories#one_cart_add'
    end
    resources :my_lists do
      delete 'product_delete'
      post 'product_add_cart', on: :collection
    end
    resources :addresses
    resources :carts do
      post 'confirm', on: :member
      get 'complite'
    end
    member do
      get 'password_edit'
      patch 'password_reset'
    end
  end
  resources :products do
    collection do
      get 'search', to: 'products#search'
      get 'quick_order', to: 'products#quick_order'
      post 'quick_order_products', to: 'products#quick_order_products'
      post 'show_create', to: 'products#show_create'
      post 'mylist_create', to: 'products#mylist_create'
    end
  end
  resources :free_pages, only: [:index]
  resources :inqueries, only: [:index] do
    get 'search', on: :collection
  end

  resources :contacts, only: [:new, :create] do
    post 'confirm', on: :collection
  end
  get 'complite', to: 'contacts#complite'
  get 'sitemap', to: 'sitemaps#sitemap'
  get 'mypage', to: 'mypages#mypage'

  # Auth0 api
  get 'api/private' => 'private#private'
  get 'api/private-scoped' => 'private#private_scoped'

  namespace :admin do
    get 'login', to: 'sessions#index'
    post 'login', to: 'sessions#login'
    post 'logout', to: 'sessions#logout'
    post 'password_reset', to: 'sessions#password_reset'
    get 'complite_message', to: 'sessions#complite_message'
    get 'dashboard', to: 'dashboards#index'
    get 'hazimeni', to: 'dashboards#hazimeni'
    post 'mongo', to: 'dashboards#mongo'
    resources :informations do
      post 'change_release', on: :member
      post 'info_title', on: :collection
      get 'download', on: :member
    end
    # post 'informations/change_release/:id', to: 'informations#change_release', as: :informations_change_release
    resources :images
    get 'banner_index', to: 'images#banner_index'
    get 'witch_new_or_edit', to: 'images#witch_new_or_edit'
    get 'banner_new', to: 'images#banner_new'
    get 'banner_edit/:id', to: 'images#banner_edit', as: 'banner_edit'
    post 'banner_create', to: 'images#banner_create'
    patch 'banner_update/:id', to: 'images#banner_update', as: 'banner_update'
    get 'product_page_edit', to: 'product_pages#edit'
    post 'product_page_create', to: 'product_pages#create'
    resources :free_pages do
      post 'change_release', on: :member
      post 'edit_change', on: :member
    end
    resources :page_contents, only: [:destroy, :create, :update]
    resources :inqueries do
      get 'select', on: :collection
    end
    resources :questions
    resources :products do
      collection do
        get 'search'
        get 'category'
        get 'category_edit'
        get 'child_category'
        post 'category_create'
        patch 'category_update'
      end
      post 'change_release', on: :member
    end
    resources :order_managements do
      collection do
        get 'user_search'
        get 'address_search'
        get 'product_search'
        get 'order_history'
        get 'order_history_search'
        post 'select_product_delete'
      end
    end
    resources :shipments do
      collection do
        get 'search'
      end
    end
    resources :members do
      collection do
        get 'search'
      end    end
    resources :groups do
      collection do
        get 'search'
      end    end
    resources :addresses do
      collection do
        get 'search'
        get 'user_search'
      end
    end
    resources :shipping_origins do
      collection do
        get 'search'
      end
    end
    resources :stock_managements do
      collection do
        get 'search'
        get 'bluk_edit'
        patch 'bluk_update'
      end
    end
    resources :shops do
      patch 'open_or_close', on: :member
    end
    resources :mail_settings
    resources :payment_method_settings
    resources :shipping_settings
    resources :cart_memos
    resources :member_ranks do
      collection do
        patch 'bluk_update'
      end
    end
    resources :holiday_settings do
      collection do
        patch 'bluk_update'
      end
    end
    resources :shop_holidays do
      post 'update_set_shop_holiday'
      patch 'update_calender_display', on: :collection
    end
    resources :users do
      get 'password_reset', on: :member
      patch 'reset', on: :member
    end
  end
end

app/models/cart.rb
class Cart < ApplicationRecord
  belongs_to :user
  has_many :cart_items
  has_many :order_histories
  has_many :products
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  def index
  end

  def edit
    @cart_items = @current_user.cart.cart_items
    total_price = 0
    @cart_items.each do |cart_item|
      total_price += cart_item.product.price * cart_item.quantity
    end
    @total_price = total_price
  end

  def show
    @now_address = @current_user.addresses.find_by(is_select_flag: true)
    unless params[:next]
      cart_item_id = params[:cart_item_id].keys.first
      update_quantity = params[:cart][:quantity][:product_quantity][cart_item_id].values.first.to_i
      @cart_item = CartItem.find(cart_item_id)
      if @cart_item.update(quantity: update_quantity)
        redirect_to edit_user_cart_path(@current_user, @current_user.cart.id)
      else
        render 'edit'
      end
    end
  end

  def confirm
    @now_address = @current_user.addresses.find_by(is_select_flag: true)

    # バリデーションチェック
    @errors = []
    if params[:use_basic_email_flg].blank? || (params[:use_basic_email_flg] != "1" && params[:use_basic_email_flg] != "2")
      @errors << "お届け先情報を選択してください。"
    end
    if params[:use_basic_email_flg] == "2" && params[:companies].blank?
      @errors << "お届け先を選択してください"
    end
    if params[:payment_method_flg].blank? || (params[:payment_method_flg] != "1" && params[:payment_method_flg] != "2")
      @errors << "お支払い方法を選択してください。"
    end
    if params[:date].blank?
      @errors << "お届け希望日を選択してください。"
    end
    if @errors.present?
      render :show and return
    end

    @use_basic_email_flg = params[:use_basic_email_flg]
    @company_select = params[:companies]

    if params[:use_basic_email_flg] == "1"
      @now_address
    else
      # 新規お届け先か
      if params[:companies] == "0"
        @new_address = {
          company_name: params[:company_name],
          department_name: params[:department_name],
          name_sei: params[:name_sei],
          name_mei: params[:name_mei],
          name_sei_kana: params[:name_sei_kana],
          name_mei_kana: params[:name_mei_kana],
          zip_code: params[:zip_code],
          prefectures: params[:prefectures],
          municipation: params[:municipation],
          address_1: params[:address_1],
          address_2: params[:address_2],
          tel: params[:tel],
          phone_number: params[:phone_number],
          address_create: params[:address_create]
        }
      else
        @address = @current_user.addresses.find_by(id: params[:companies]) # 既存のデータ
      end
    end
    # お支払い方法
    @payment_method = params[:payment_method_flg]
    # お届け希望日
    @date = params[:date]
    # 備考
    @memo = params[:remakes]

    # 表示
    @cart_items = @current_user.cart.cart_items
    total_price = 0
    @cart_items.each do |cart_item|
      total_price += cart_item.product.price * cart_item.quantity
    end
    @product_total_price = total_price
    @shouhi_zei = (@product_total_price * 0.1).ceil
    @total_price = @product_total_price + @shouhi_zei
    @address_attribute = params[:companies].to_i == 0 ? params[:address] : Address.find(params[:companies])
    @date_array = date_select_box.select {|v| v == params[:date].to_i} if params[:date] != "99"
    @date = @date_array.flatten.first if @date_array != nil
  end

  def create
    @address_attribute = params[:companies].to_i == 0 ? params[:addresses] : Address.find(params[:companies])

    ActiveRecord::Base.transaction do
      # 宛先新規作成+チェックが付いてた場合アドレス作成
      if params[:use_basic_email_flg].to_i == 2
        if params[:companies].to_i == 0 && params[:address][:address_create] == "true"
          @address = Address.new(
            company_name: params[:address][:company_name],
            department_name: params[:address][:department_name],
            name_sei: params[:address][:name_sei],
            name_mei: params[:address][:name_mei],
            name_sei_kana: params[:address][:name_sei_kana],
            name_mei_kana: params[:address][:name_mei_kana],
            zip_code: params[:address][:zip_code],
            prefectures: params[:address][:prefectures],
            municipation: params[:address][:municipation],
            address_1: params[:address][:address_1],
            address_2: params[:address][:address_2],
            tel: params[:address][:tel],
            phone_number: params[:address][:phone_number],
            user_id: @current_user.id,
            is_select_flag: false,
            company_code: SecureRandom.alphanumeric(6),
            department_code: SecureRandom.alphanumeric(6),
            fax: nil,
            delivery_id: nil
          )
          @address.save!
        else
          @address = @current_user.addresses.find_by(id: params[:companies])
        end
      else
        @address = @current_user.addresses.find_by(is_select_flag: true)
      end

      # order_history, order_history_products, shipment, shipment_productをここで作成

      # order_numberはランダムで作成(同じのがあった場合loopして新しく作る)
      order_history_number = SecureRandom.alphanumeric()
      loop do
        if OrderHistory.find_by(order_number: order_history_number).blank?
          break
        end
        order_history_number = SecureRandom.alphanumeric()
      end

      invoice_number = SecureRandom.alphanumeric()
      loop do
        if OrderHistory.find_by(invoice_number: invoice_number).blank?
          break
        end
        invoice_number = SecureRandom.alphanumeric()
      end

      # memo: 備考, status: 1(出荷前), payment: 1(入金待ち), allocation_status: 1(未引当), shipping_status: 1(未処理), postage_confirmation: 1(確認済み)
      @order_history = OrderHistory.new(
        order_number: order_history_number,
        memo: params[:remakes],
        status: 1,
        user_id: @current_user.id,
        order_date_start: DateTime.now,
        preferred_date_flg: params[:preferred_date_flg],
        preferred_date_start: @date,
        invoice_number: invoice_number,
        payment_method: params[:payment_method],
        payment: 1,
        allocation_status: 1,
        shipping_status: 1,
        postage_confirmation: 1,
        cancel_flg: 0,
        address_id: @address.id
      )
      @order_history.save!

      # order_history_products作成と在庫の減少
      params[:cart_item].each do |cart_item|
        product = Product.find(cart_item["product_id"])
        stock = (product.stock_management.stock - cart_item["quantity"].to_i)
        if stock < 0
          raise StandardError
        end
        product.stock_management.update!(stock: stock)
        @order_history_products = OrderHistoryProduct.new(
          order_history_id: @order_history.id,
          product_id: product.id,
          num: cart_item["quantity"]
        )
        @order_history_products.save!
      end

      # 初期設定(has_one: order_history追加、order_history_id追加)
      @shipment = Shipment.new(
        shipping_status: 1,
        allocation_status: 1,
        expected_shipping_date_flg: params[:preferred_date_flg],
        expected_shipping_date: @date
        # order_history_id: @order_history.id
      )
      @shipment.save!

      params[:cart_item].each do |cart_item|
        @shipment_products = ShipmentProduct.new(
          shipment_id: @shipment.id,
          product_id: cart_item["product_id"],
          num: cart_item["quantity"],
          status: 1
        )
        @shipment_products.save!
      end

      #
      @order_history.update(shipment_id: @shipment.id)

      # カートの商品全て削除
      @current_user.cart.cart_items.destroy_all
    end
    # 成功時の処理(todo ユーザーにメールを送信する)
    redirect_to user_cart_complite_path(@current_user, @current_user.cart.id, order_history_id: @order_history.id)
  rescue
    @cart_items = @current_user.cart.cart_items
    @error = "システムエラーが発生しました。管理者に問い合わせください。"
    render :confirm and return
  end

  def complite
    order_history = OrderHistory.find(params[:order_history_id])
    @order_number = order_history.order_number
    NotificationMailer.send_purchase_complite(current_user, order_history).deliver
  end

  def destroy
    cart_item = CartItem.find(params[:cart_item_id])
    if cart_item.destroy!
      redirect_to edit_user_cart_path(@current_user, @current_user.cart.id)
    else
      render edit_user_cart_path(@current_user, @current_user.cart.id)
    end
  end

    private

    def date_select_box
      @date_select = [['指定なし',99]]
      @current_date = Date.today.strftime("%Y/%m/%d/")
      (0..10).each do |i|
        @date_select << [(Date.today+(i+5)).strftime("%Y/%m/%d"), i]
      end
      return @date_select
    end
end

app/helpers/carts_helper.rb
module CartsHelper
  def data_select_box
    # お届け日のセレクトの部分作成
    date_select = [['指定なし',99]]
    # current_date = Date.today.strftime("%Y/%m/%d/")
    (0..10).each do |i|
      date_select << [(Date.today+(i+5)).strftime("%Y/%m/%d"), i]
    end
    return date_select
  end

  def user_address_select
    # お届け先のセレクトボックス作成
    addresses_name = [['新規お届け先',0]]
    @current_user.addresses.each do |address|
      addresses_name << [address.company_name, address.id]
    end
    return addresses_name
  end
end

app/views/carts/complite.html.slim
.container
  .row
    .col-12
      br
      p.border-bottom ご注文完了
      br
      br
      br
      p ご注文ありがとうございます。
      p 注文番号：#{@order_number}
      p ご登録のメールアドレス宛に、ご注文確認のメールをお送りいたします。
      br
      .row
        .col-3
        .col-3
          = link_to 'ログアウト', logout_path, method: :post, class: "form-control text-center"
        .col-3
          = link_to 'トップへ', root_path, class: "form-control text-center"
        .col-3

app/views/carts/confirm.html.slim
.container
  .row
    .col-12
      = form_with url: user_carts_path, method: :post, local: true do |f|
        br
        h3.border-bottom.border-5.border-info Step3 最終確認
        p.text-right カートの情報 - 情報入力 - 最終確認・ご注文

        p 以下の内容でよろしければ、下の「この内容で注文する」ボタンを押してください。
        .text-danger
          | ※他の画面に遷移するとご入力いただいた情報が失われてしまうことがありますのでご注意ください。

        - if @error.present?
          .alert
            = @error

        .border.pt-3
          table.table.table-bordered.mx-auto(style="width:95%;")
            tr.bg-secondary
              th 商品番号
              th 品名
              th 税率
              th 単価（税抜）
              th 数量
              th 金額（税抜）
            - @cart_items.each do |cart_item|
              tr
                td = cart_item.product.product_number
                td = cart_item.product.name
                td 10%
                td
                  = cart_item.product.price
                  | 円
                td = cart_item.quantity
                td
                  = cart_item.product.price * cart_item.quantity
                  | 円
                  = f.hidden_field "cart_item[][product_id]", value: cart_item.product_id
                  = f.hidden_field "cart_item[][quantity]", value: cart_item.quantity
          br
          .row
            .col-md-7
            .col-md-5
              table.table.table-borderless
                tbody
                  tr
                    th.bg-info 商品金額（税抜）10%
                    td
                      = @product_total_price
                      | 円
                  tr
                    th.bg-info 送料
                    td 1000円
                  tr
                    th.bg-info 代引手数料
                    td 無料
                  tr
                    th.bg-info 消費税 10%
                    td
                      = @shouhi_zei
                      | 円
                  tr.border-top
                    th.bg-info 合計金額
                    td
                      = @total_price
                      | 円
        br
        p.border-bottom お客様情報
        .border.pt-3
          table.table.table-borderless.mx-auto(style="width:95%;")
            tr
              th.text-right.bg-info(style="width:30%;") 会社名
              td.border-bottom = @current_user.company_name
            tr
              th.text-right.bg-info 部署名
              td.border-bottom = @current_user.department_name
            tr
              th.text-right.bg-info 担当者名
              td.border-bottom
                | #{@current_user.name_sei + @current_user.name_mei}
            tr
              th.text-right.bg-info 電話番号
              td.border-bottom = @current_user.phone_number
        br
        p.border-bottom お届け先情報
        - if params[:use_basic_email_flg].to_i == 2
          = f.fields_for :addresses do |ff|
            .border.pt-3
              table.table.table-borderless.mx-auto(style="width:95%;")
                tr
                  th.text-right.bg-info(style="width:30%;") 会社名
                  td.border-bottom = @address_attribute[:company_name]
                  = ff.hidden_field :company_name, value: @address_attribute[:company_name]
                tr
                  th.text-right.bg-info お名前
                  td.border-bottom = "#{@address_attribute[:name_sei] + @address_attribute[:name_mei]}"
                  = ff.hidden_field :name_sei, value: @address_attribute[:name_sei]
                  = ff.hidden_field :name_mei, value: @address_attribute[:name_mei]
                tr
                  th.text-right.bg-info 郵便番号
                  td.border-bottom = @address_attribute[:zip_code]
                  = ff.hidden_field :zip_code, value: @address_attribute[:zip_code]
                tr
                  th.text-right.bg-info 住所
                  td.border-bottom = "#{@address_attribute[:prefectures] + @address_attribute[:municipation] + @address_attribute[:address_1] + @address_attribute[:address_2]}"
                  = ff.hidden_field :prefectures, value: @address_attribute[:prefectures]
                  = ff.hidden_field :municipation, value: @address_attribute[:municipation]
                  = ff.hidden_field :address_1, value: @address_attribute[:address_1]
                  = ff.hidden_field :address_2, value: @address_attribute[:address_2]
                tr
                  th.text-right.bg-info 電話番号
                  td.border-bottom = @address_attribute[:tel]
                  = ff.hidden_field :tel, value: @address_attribute[:tel]
                tr
                  th.text-right.bg-info 携帯番号
                  td.border-bottom = @address_attribute[:phone_number]
                  = ff.hidden_field :phone_number, value: @address_attribute[:phone_number]
              = f.hidden_field :use_basic_email_flg, value: 2
              = f.hidden_field :address_create, value: params[:address_create]
        - else
          .border.pt-3
            table.table.table-borderless.mx-auto(style="width:95%;")
              tr
                th.text-right.bg-info(style="width:30%;") お届け先
                td.border-bottom お客様情報と同じ住所に配送する
                = hidden_field_tag :use_basic_email_flg, value: 1
        br
        p.border-bottom お支払い方法
        .border.pt-3
          table.table.table-borderless.mx-auto(style="width:95%;")
            tr
              th.text-right.bg-info(style="width:30%;") お支払い方法
              - if params[:date] == "99"
                td.border-bottom 締め払い
                = f.hidden_field :payment_method, value: 1
              - else
                td.border-bottom 御社規定に従います
                = f.hidden_field :payment_method, value: 2
        br
        p.border-bottom お届け希望日時指定
        .border.pt-3
          table.table.table-borderless.mx-auto(style="width:95%;")
            tr
              th.text-right.bg-info(style="width:30%;") お届け希望日
              - if params[:date] == "99"
                td.border-bottom 指定なし
                = f.hidden_field :preferred_date_flg, value: 0
                = f.hidden_field :date, value: nil
              - else
                td.border-bottom = @date
                = f.hidden_field :preferred_date_flg, value: 1
                = f.hidden_field :date, value: @date
        br
        p.border-bottom 備考・連絡事項等
        .border.pt-3
          table.table.table-borderless.mx-auto(style="width:95%;")
            tr
              th.text-right.bg-info(style="width:30%;") 備考
              td.border-bottom
                = simple_format(params[:remakes])
                = f.hidden_field :remakes, value: params[:remakes]
        br
        p 以上の内容でよろしければ、下の「この内容で注文する」ボタンを押してください。
        .row
          .col-3
          .col-3
            = link_to '訂正する', edit_user_cart_path(@current_user, @current_user.cart.id), class: "form-control text-center"
          .col-3
            = f.hidden_field :companies, value: params[:companies]
            = f.submit 'この内容で注文する', class: "form-control"
          .col-3

app/views/carts/edit.html.slim
.container
  .row
    .col-12
      - if @cart_items.present?
        br
        h3.border-bottom.border-5.border-info Step1 カートの確認
        p カートには、以下の商品が入っています。
        p 商品の数量を変更する場合は、数量を変更し「変更」ボタンを押してください。
        p.text-right カートの情報 - 情報入力 - 最終確認・ご注文

        = form_with model: Cart, url: user_cart_path, method: :get, local: true, class: "form-horizontal" do |f|
          .border
            p.pl-3.py-3 カートの内容
            table.table.table-bordered.text-center.mx-auto(style="width:95%;")
              thead
                tr.d-flex.no-gutters
                  th.col-sm-1 画像
                  th.col-sm-1 商品番号
                  th.col-sm-5 品名
                  th.col-sm-1
                    | 単価
                    div
                    | （税抜）
                  th.col-sm-2 数量
                  th.col-sm-1
                    | 金額
                    div
                    |（税抜）
                  th.col-sm-1 取消
              tbody
                - @cart_items.each do |cart_item|
                  = f.hidden_field "cart_item_id[][#{cart_item.id}]", value: cart_item.id
                  tr.d-flex.no-gutters
                    td
                      col-sm-1
                        h-100
                          = image_tag(cart_item.product.image.to_s, class: "image-max-size")
                    td.col-sm-1.text-break = cart_item.product.product_number
                    td.col-sm-5 = link_to cart_item.product.name, product_path(cart_item.product)
                    td.col-sm-1
                      = cart_item.product.price
                      | 円
                    td.col-sm-2
                      .form-inline
                        = f.fields_for :quantity do |ff|
                          = ff.number_field "product_quantity[#{cart_item.id}][#{cart_item.quantity}]", value: cart_item.quantity, class: "col-sm-7 form-control"
                          = ff.submit '変更', name: "cart_item_id[#{cart_item.id}]", class: "col-sm-5 form-control"
                    td.col-sm-1
                      = cart_item.product.price * cart_item.quantity
                      | 円
                    td.col-sm-1
                      = link_to '取消', user_cart_path(@current_user, cart_item_id: cart_item.id), method: :delete, class: "btn btn-primary"
            .row
              .col-md-7
              .col-md-5.pb-5.pr-5.pt-2
                .row
                  .col-md-7.bg-info.text-right
                    | 商品金額（税抜）10%
                  .col-md-5
                    | #{@total_price}円
                  .col-md-7.bg-info.text-right
                    | 送料
                  .col-md-5
                    | ※step3でご確認ください
                  .col-md-7.border-bottom.bg-info.text-right
                    | 消費税 10%
                  .col-md-5.border-bottom
                    | #{(@total_price*0.1).ceil}円
                  .col-md-7.bg-info.text-right
                    | 合計金額
                  .col-md-5
                    | #{@total_price + 1000}円
          br
          .row
            .col-3
            .col-3
              = link_to '戻る', root_path, class: "form-control text-center"
            .col-3
              = f.submit '注文画面に進む', name: 'next', class: "form-control"
            .col-3
        br
        .text-right = link_to 'ページトップに', root_path

      - else
        p ご注文内容をご確認ください。
        p お客様のカートには商品が入っておりません。

app/views/carts/index.html.slim
p カートページ

p Step1 カートの確認

p カートには、以下の商品が入っています。
p 商品の数量を変更する場合は、数量を変更し「変更」ボタンを押してください。

h2 カートの内容
p 画像　品番	品名	単価（税抜）	数量	金額（税抜）	取消

app/views/carts/purchase_confirm.html.slim
h2 Step3 最終確認

p 以下の内容でよろしければ、下の「この内容で注文する」ボタンを押してください。
p ※他の画面に遷移するとご入力いただいた情報が失われてしまうことがありますのでご注意ください。

p 品番	品名	単価（税抜）	数量	金額（税抜）
- @cart_items.each do |cart_item|
  = cart_item.product.product_number
  = cart_item.product.name
  = cart_item.product.price
  = cart_item.product.price * cart_item.quantity

p 商品金額（税抜）#{@total_price}円
p 送料 1000円
p 消費税 1000円
p 合計金額 #{@total_price + 1000 + 1000}円

h2 お客様情報
p 会社名 #{@current_user.company_name}
p 部署名 #{@current_user.department_name}
p 担当者名 #{@current_user.contact_name}
p 電話番号 #{@current_user.phone_number}


h2 お届け先情報
p if もし変更がない場合は
p お届け先	お客様情報と同じ住所に配送する
p else 変更がある場合は
p お届け先情報を入れていく

h2 お届け希望日時指定・備考
p お届け希望日	指定なし
p 備考

p 以上の内容でよろしければ、下の「この内容で注文する」ボタンを押してください。

= link_to '訂正する', edit_user_cart_path(@current_user, @current_user.cart_id)
= link_to 'この内容で注文する', user_cart_complite_path(@current_user, @current_user.cart_id)