config/routes.rb
Rails.application.routes.draw do
  get 'auth/:provider/callback', to: 'sessions#create'
  get 'auth/failure', to: redirect('/login')
  get 'signout', to: 'sessions#destroy', as: 'signout'
  get 'sessions/new'
  get 'sessions/create'
  get 'sessions/destroy'
  root 'top_pages#index'
  get 'top_pages/:id/download', to: 'top_pages#download', as: 'top_pages'
  get 'login', to: 'sessions#index'
  post 'login', to: 'sessions#login'
  post 'logout', to: 'sessions#logout'
  post 'password_reset', to: 'sessions#password_reset'
  get 'reset_password/:user_id', to: 'sessions#reset_password'
  post 'reset_user_password/:user_id', to: 'sessions#reset_user_password'
  get 'complite_message', to: 'sessions#complite_message'
  resources :users do
    resources :order_histories do
      get 'search', on: :collection
      post 'cart_add', on: :collection
      post 'one_cart_add', to: 'order_histories#one_cart_add'
    end
    resources :my_lists do
      delete 'product_delete'
      post 'product_add_cart', on: :collection
    end
    resources :addresses
    resources :carts do
      post 'confirm', on: :member
      get 'complite'
    end
    member do
      get 'password_edit'
      patch 'password_reset'
    end
  end
  resources :products do
    collection do
      get 'search', to: 'products#search'
      get 'quick_order', to: 'products#quick_order'
      post 'quick_order_products', to: 'products#quick_order_products'
      post 'show_create', to: 'products#show_create'
      post 'mylist_create', to: 'products#mylist_create'
    end
  end
  resources :free_pages, only: [:index]
  resources :inqueries, only: [:index] do
    get 'search', on: :collection
  end

  resources :contacts, only: [:new, :create] do
    post 'confirm', on: :collection
  end
  get 'complite', to: 'contacts#complite'
  get 'sitemap', to: 'sitemaps#sitemap'
  get 'mypage', to: 'mypages#mypage'

  # Auth0 api
  get 'api/private' => 'private#private'
  get 'api/private-scoped' => 'private#private_scoped'

  namespace :admin do
    get 'login', to: 'sessions#index'
    post 'login', to: 'sessions#login'
    post 'logout', to: 'sessions#logout'
    post 'password_reset', to: 'sessions#password_reset'
    get 'complite_message', to: 'sessions#complite_message'
    get 'dashboard', to: 'dashboards#index'
    get 'hazimeni', to: 'dashboards#hazimeni'
    post 'mongo', to: 'dashboards#mongo'
    resources :informations do
      post 'change_release', on: :member
      post 'info_title', on: :collection
      get 'download', on: :member
    end
    # post 'informations/change_release/:id', to: 'informations#change_release', as: :informations_change_release
    resources :images
    get 'banner_index', to: 'images#banner_index'
    get 'witch_new_or_edit', to: 'images#witch_new_or_edit'
    get 'banner_new', to: 'images#banner_new'
    get 'banner_edit/:id', to: 'images#banner_edit', as: 'banner_edit'
    post 'banner_create', to: 'images#banner_create'
    patch 'banner_update/:id', to: 'images#banner_update', as: 'banner_update'
    get 'product_page_edit', to: 'product_pages#edit'
    post 'product_page_create', to: 'product_pages#create'
    resources :free_pages do
      post 'change_release', on: :member
      post 'edit_change', on: :member
    end
    resources :page_contents, only: [:destroy, :create, :update]
    resources :inqueries do
      get 'select', on: :collection
    end
    resources :questions
    resources :products do
      collection do
        get 'search'
        get 'category'
        get 'category_edit'
        get 'child_category'
        post 'category_create'
        patch 'category_update'
      end
      post 'change_release', on: :member
    end
    resources :order_managements do
      collection do
        get 'user_search'
        get 'address_search'
        get 'product_search'
        get 'order_history'
        get 'order_history_search'
        post 'select_product_delete'
      end
    end
    resources :shipments do
      collection do
        get 'search'
      end
    end
    resources :members do
      collection do
        get 'search'
      end    end
    resources :groups do
      collection do
        get 'search'
      end    end
    resources :addresses do
      collection do
        get 'search'
        get 'user_search'
      end
    end
    resources :shipping_origins do
      collection do
        get 'search'
      end
    end
    resources :stock_managements do
      collection do
        get 'search'
        get 'bluk_edit'
        patch 'bluk_update'
      end
    end
    resources :shops do
      patch 'open_or_close', on: :member
    end
    resources :mail_settings
    resources :payment_method_settings
    resources :shipping_settings
    resources :cart_memos
    resources :member_ranks do
      collection do
        patch 'bluk_update'
      end
    end
    resources :holiday_settings do
      collection do
        patch 'bluk_update'
      end
    end
    resources :shop_holidays do
      post 'update_set_shop_holiday'
      patch 'update_calender_display', on: :collection
    end
    resources :users do
      get 'password_reset', on: :member
      patch 'reset', on: :member
    end
  end
end

app/models/image.rb
class Image < ApplicationRecord
  # is_banner_flg 真偽値 trueなら表示させる
  mount_uploader :image, ImageUploader
  
  validates :image, presence: true
  validates :is_banner_flg, inclusion: { in: [true, false] }
end

app/controllers/admin/images_controller.rb
class Admin::ImagesController < ApplicationController
  def index
    # 初期値がない場合は設定する
    params[:page] = params[:page].blank? ? 1 : params[:page]
    params[:per] = params[:per].blank? ? 25 : params[:per]
    @page = params[:page]
    @per = params[:per]

    @image = Image.new
    @images = Image.all.page(@page).per(@per)
  end

  def create
    @images = Image.all.page(@page).per(@per)
    @image = Image.new(
      image: params[:image][:image],
      name: params[:image][:image].original_filename,
      comment: params[:image][:comment],
      is_banner_flg: params[:image][:is_banner_flg]
    )
    if @image.save
      url = "aタグで括るためhttps://から始まるurl指定"
      if @image.update(url: url)
        redirect_to admin_images_path
      else
        render 'index' and return
      end
    else
      render 'index' and return
    end
  end

  def destroy
  end

  def banner_index
    @images = Image.all
  end

  def witch_new_or_edit
    if params[:image][:image_name].present?
      redirect_to admin_banner_edit_path(params[:image][:image_name])
    else
      redirect_to admin_banner_new_path
    end
  end

  def banner_new
    @images = Image.all
    @banner = Banner.new
  end

  def banner_edit
    @images = Image.all
    @banner = Banner.find(params[:id])
  end

  def banner_create
    Banner.create(image: params[:banner][:image], name: "banana1", hyoji_area: 2, comment: "バナー下")
    redirect_to root_path
  end

  def banner_update
    @images = Image.all
    @banner = Banner.find(params[:id])
    image = Image.find_by(name: params[:banner][:image_name])
    if image.blank?
      image = Image.first
    end

    if @banner.update(name: params[:banner][:name], comment: params[:banner][:comment], hyoji_area: params[:banner][:hyoji_area], image_id: image.id)
      redirect_to admin_banner_index_path
    else
      render 'banner_edit'
    end
  end

  private

  def banner_upload
    params.require(:image).permit(:image)
  end
end

app/helpers/admin/images_helper.rb
module Admin::ImagesHelper
end

app/views/admin/images/banner.html.slim
p バナー・リンク管理
p サイトに表示されるバナーやリンクを管理します。
p 新しく表示位置を追加するときは、表示位置を「新規登録」にし、表示位置名称を入力し、「追加」ボタンを押してください。ただし表示するにはテンプレート側の設定も必要です。
p 画像を登録する場合は、あらかじめ「画像管理」にて画像をアップロードしてください。
p 全ての編集が終わりましたら、「サイト更新」ボタンを押し、情報を更新してください。「一時削除」、「一時保存」だけでは、データは更新されません。

p 表示位置

app/views/admin/images/banner_edit.html.slim
.container
  .row
    = render 'layouts/admin_left_menu'
    .col-10
      br
        p.bg-secondary ◎ バナー・リンク管理
        div
          ul.border.border-5.border-muted
            p サイトに表示されるバナーやリンクを管理します。
            li.small 新しく表示位置を追加するときは、表示位置を「新規登録」にし、表示位置名称を入力し、「追加」ボタンを押してください。ただし表示するにはテンプレート側の設定も必要です。
            li.small 画像を登録する場合は、あらかじめ「画像管理」にて画像をアップロードしてください。
            li.small 全ての編集が終わりましたら、「サイト更新」ボタンを押し、情報を更新してください。「一時削除」、「一時保存」だけでは、データは更新されません。

        / セレクトボックス選択で画面を変える（多分ajaxとか？）
        = form_with model: Banner, url: admin_banner_update_path, method: :patch, local: true do |f|
          table.table.table-bordered.bg-light
            tbody
              tr
                th = f.label "表示位置"
                td.bg-white = f.collection_select :banner_id, Banner.all, :id, :name
              tr
                th = f.label "表示位置名称"
                td.bg-white = f.text_field :banner_name
              tr.text-center
                th[colspan="2"] = f.submit '変更'

        table.table.table-bordered.bg-light
          tbody
            tr
              = form_with model: Image, url: admin_banner_edit_path, method: :get, local: true do |f|
                th = f.label 'バナー・リンク一覧'
                td.bg-white
                  = f.collection_select :id, @images, :id, :name, { include_blank: "新規登録", selected: 0 }
                  div
                  = f.submit '参照'
            tr
              th 内容
              td.bg-white
                = form_with model: @banner, url: admin_banner_update_path(@banner), method: :patch, local: true do |f|
                  table.table.table-bordered.bg-light
                    tbody
                      tr
                        th.max-width-30 = f.label '名称（必須）'
                        td.bg-white.max-width-70 = f.text_field :name, class: 'image-max-size'
                      tr
                        th = f.label 'バナー画像（必須）'
                        td.bg-white
                          = f.text_field :image_name
                          div
                          | * 画像名を入力してください。
                      tr
                        th = f.label '表示箇所'
                        td.bg-white = f.number_field :hyoji_area, class: 'image-max-size'
                      tr
                        th = f.label 'コメント'
                        td.bg-white = f.text_area :comment, class: 'text-area'
                  div
                    = f.submit '保存'

app/views/admin/images/banner_index.html.slim
.container
  .row
    = render 'layouts/admin_left_menu'
    .col-10
      br
        p.bg-secondary ◎ バナー・リンク管理
        div
          ul.border.border-5.border-muted
            p サイトに表示されるバナーやリンクを管理します。
            li.small 新しく表示位置を追加するときは、表示位置を「新規登録」にし、表示位置名称を入力し、「追加」ボタンを押してください。ただし表示するにはテンプレート側の設定も必要です。
            li.small 画像を登録する場合は、あらかじめ「画像管理」にて画像をアップロードしてください。
            li.small 全ての編集が終わりましたら、「サイト更新」ボタンを押し、情報を更新してください。「一時削除」、「一時保存」だけでは、データは更新されません。

        = form_with model: Banner, url: admin_banner_update_path(:banner_id), method: :patch, local: true do |f|
          table.table.table-bordered.bg-light
            tbody
              tr
                / todo ajaxで変化する
                th = f.label "表示位置"
                td.bg-white = f.collection_select :banner_id, Banner.all, :id, :name
              tr
                / todo こっちも上が変われば変わる
                th = f.label "表示位置名称"
                td.bg-white = f.text_field :banner_name
              tr.text-center
                th[colspan="2"] = f.submit '変更'

        table.table.table-bordered.bg-light
          tbody
            tr
              = form_with model: Image, url: admin_witch_new_or_edit_path, method: :get, local: true do |f|
                th = f.label 'バナー・リンク一覧'
                td.bg-white
                  = f.collection_select :image_name, @images, :id, :name, { include_blank: "新規登録", selected: 0 }
                  div
                  = f.submit '参照'

app/views/admin/images/banner_new.html.slim
.container
  .row
    = render 'layouts/admin_left_menu'
    .col-10
      br
        p.bg-secondary ◎ バナー・リンク管理
        div
          ul.border.border-5.border-muted
            p サイトに表示されるバナーやリンクを管理します。
            li.small 新しく表示位置を追加するときは、表示位置を「新規登録」にし、表示位置名称を入力し、「追加」ボタンを押してください。ただし表示するにはテンプレート側の設定も必要です。
            li.small 画像を登録する場合は、あらかじめ「画像管理」にて画像をアップロードしてください。
            li.small 全ての編集が終わりましたら、「サイト更新」ボタンを押し、情報を更新してください。「一時削除」、「一時保存」だけでは、データは更新されません。

        / セレクトボックス選択で画面を変える（多分ajaxとか？）
        = form_with model: Banner, url: admin_banner_update_path, method: :patch, local: true do |f|
          table.table.table-bordered.bg-light
            tbody
              tr
                th = f.label "表示位置"
                td.bg-white = f.collection_select :banner_id, Banner.all, :id, :name
              tr
                th = f.label "表示位置名称"
                td.bg-white = f.text_field :banner_name
              tr.text-center
                th[colspan="2"] = f.submit '変更'

        table.table.table-bordered.bg-light
          tbody
            tr
              = form_with model: Image, url: admin_banner_edit_path, method: :get, local: true do |f|
                th = f.label 'バナー・リンク一覧'
                td.bg-white
                  = f.collection_select :id, @images, :id, :name, { include_blank: "新規登録", selected: 0 }
                  div
                  = f.submit '参照'
            tr
              th 内容
              td.bg-white
                = form_with model: @banner, url: admin_banner_create_path, method: :post, local: true do |f|
                  table.table.table-bordered.bg-light
                    tbody
                      tr
                        th.max-width-30 = f.label '名称（必須）'
                        td.bg-white.max-width-70 = f.text_field :name, class: 'image-max-size'
                      tr
                        th = f.label 'バナー画像（必須）'
                        td.bg-white
                          = f.text_field :image_name
                          div
                          | * 画像名を入力してください。
                      tr
                        th = f.label '表示箇所'
                        td.bg-white = f.number_field :hyoji_area, class: 'image-max-size'
                      tr
                        th = f.label 'コメント'
                        td.bg-white = f.text_area :comment, class: 'text-area'
                  div
                    = f.submit '保存'

app/views/admin/images/index.html.slim
.container
  .row
    = render 'layouts/admin_left_menu'
    .col-10
      br
        p.bg-secondary ◎ 画像管理
        div
          ul.border.border-5.border-muted
            p サイトで使用する画像を一括管理することができます。
            li.small アップロードした画像は、商品説明などのHTMLに対応した編集欄で使用が可能です。その場合は登録画像一覧に表示されているURLをコピーしてお使いください。
            li.small 画像ファイルは、png、jpg、gifに対応。ただし、アニメーションGIFやJPEG-2000、Lossless JPEG、CMYK等には対応していません。適切なフォーマットで書き出してください。
            li.small アップ可能な最大ファイルサイズは、約20.0 MBです。

        - if @image.errors.any?
          .alert
            - @image.errors.each do |message|
              li = message
        .border
          p.bg-secondary 画像アップロード
          = form_with model: @image, url: admin_images_path, method: :post, local: true do |f|
            = f.file_field :image
            = f.label "※ファイル名は半角英数字にしてください。※アップロードできるファイルの形式は、画像ファイル（gif,jpgのみ）です。※画像はそのままのサイズでアップロードされます。"
            div
            = f.text_field :comment
            div
            = f.label '※画像にコメントを残す場合記載してください。'
            div
            = f.hidden_field :is_banner_flg, value: false
            = f.submit '登録する'
        br

        table.table-sm.table-bordered.bg-light.image-max-size
          thead
            tr
              th[colspan="3"] 登録画像一覧（表示 ： 数字昇順 ＋ ABC順）
            tr
              - if params[:per] == "25"
                th[colspan="3"]
                  .text-right
                    | 表示件数：
                    | 25件
                    = link_to ' 50件', admin_images_path(per: 50)
                    = link_to ' 100件', admin_images_path(per: 100)
              - elsif params[:per] == "100"
                th[colspan="3"]
                  .text-right
                    | 表示件数：
                    = link_to '25件 ', admin_images_path(per: 25)
                    = link_to '50件 ', admin_images_path(per: 50)
                    | 100件
              - else
                th[colspan="3"]
                  .text-right
                    | 表示件数：
                    = link_to '25件 ', admin_images_path(per: 25)
                    | 50件
                    = link_to ' 100件', admin_images_path(per: 100)
            tr
              th サムネイル画像
              th URL
              th.text-nowrap 削除
          tbody
            - @images.each do |i|
              tr
                td = image_tag(i.image.to_s, class: "admin-image-size")
                td = i.url
                td = link_to "削除", admin_image_path(i.id), method: :delete
          = paginate @images